schema_version = "1.0.0"

# Example of manifest file for a Blender extension
# Change the values according to your extension
id = "motion_inspector"
version = "0.1.1"
name = "Motion inspector"
tagline = "Inspect F-Curves and animated object movement"
maintainer = "R.G.B.it aka Chalouek"
type = "add-on"

# # Optional: link to documentation, support, source files, etc
# website = "https://extensions.blender.org/add-ons/my-example-package/"

tags = ["Animation", "User Interface"]

blender_version_min = "4.2.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]